// <auto-generated />
using System;
using CentralDeErros.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentralDeErros.Api.Migrations
{
    [DbContext(typeof(ErroDbContext))]
    [Migration("20191112234014_CentralErros")]
    partial class CentralErros
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentralDeErros.Api.Models.Ambiente", b =>
                {
                    b.Property<int>("Ambiente_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome_Ambiente")
                        .IsRequired()
                        .HasColumnName("ambiente")
                        .HasMaxLength(30);

                    b.HasKey("Ambiente_Id");

                    b.ToTable("ambiente");
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.Error", b =>
                {
                    b.Property<int>("Situacao_Id")
                        .HasColumnName("situacao_id");

                    b.Property<int>("Ambiente_Id")
                        .HasColumnName("ambiente_id");

                    b.Property<int>("Level_Id")
                        .HasColumnName("level_id");

                    b.Property<int>("AmbienteId");

                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<int>("LevelId");

                    b.Property<int>("OcorrenciaId");

                    b.Property<int>("Ocorrencia_Id")
                        .HasColumnName("ocorrencia_id");

                    b.Property<int>("SituacaoId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("titulo")
                        .HasMaxLength(200);

                    b.HasKey("Situacao_Id", "Ambiente_Id", "Level_Id");

                    b.HasAlternateKey("Id");

                    b.HasIndex("AmbienteId");

                    b.HasIndex("LevelId");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("SituacaoId");

                    b.ToTable("error");
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.Level", b =>
                {
                    b.Property<int>("Level_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome_Level")
                        .IsRequired()
                        .HasColumnName("level")
                        .HasMaxLength(30);

                    b.HasKey("Level_Id");

                    b.ToTable("level");
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.OcorrenciaErro", b =>
                {
                    b.Property<int>("Ocorrencia_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_Hora")
                        .HasColumnName("data_hora");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnName("detalhes")
                        .HasMaxLength(2000);

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnName("origem")
                        .HasMaxLength(200);

                    b.Property<int>("UserId");

                    b.Property<int>("User_Id")
                        .HasColumnName("user_id");

                    b.HasKey("Ocorrencia_Id");

                    b.HasIndex("UserId");

                    b.ToTable("ocorrenciaerro");
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.Situacao", b =>
                {
                    b.Property<int>("Situacao_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome_Situacao")
                        .IsRequired()
                        .HasColumnName("situacao")
                        .HasMaxLength(30);

                    b.HasKey("Situacao_Id");

                    b.ToTable("situacao");
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(200);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("token")
                        .HasMaxLength(40);

                    b.HasKey("User_Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.Error", b =>
                {
                    b.HasOne("CentralDeErros.Api.Models.Ambiente", "Ambiente")
                        .WithMany("Errors")
                        .HasForeignKey("AmbienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CentralDeErros.Api.Models.Level", "Level")
                        .WithMany("Errors")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CentralDeErros.Api.Models.OcorrenciaErro", "OcorrenciaErros")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CentralDeErros.Api.Models.Situacao", "Situacao")
                        .WithMany("Errors")
                        .HasForeignKey("SituacaoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CentralDeErros.Api.Models.OcorrenciaErro", b =>
                {
                    b.HasOne("CentralDeErros.Api.Models.User", "User")
                        .WithMany("OcorrenciaErros")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
